#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 15 16:53:58 2018

@author: Alicia
"""

def majority(arr):
  """
  arr: is the list containing the letters from which you have to select
  the one that most appears
  return: the item that appears most or None if there is no winner
  """
  
  print(arr.count(str(item) for item in arr))
  return None

majority(["A","A","A","B"])